### ISSUE TITLE
本リポジトリで公開されているファイルについて

### ISSUE THREAD

**Issue by knokmki612** [k1o0b1a9/card_specification_func#2]
興味深いプロジェクトを公開されており拝見しました。ありがとうございます。

リポジトリで管理されているファイルを探索したところ、以下について公開して問題のないファイルか気になったので質問させてください。

- CSVファイル https://github.com/k1o0b1a9/card_specification_func/tree/main/specification 
- サービスアカウントキー https://github.com/k1o0b1a9/card_specification_func/tree/main/path
- dotenvファイル https://github.com/k1o0b1a9/card_specification_func/blob/main/.env

もし具体的なサンプルを用意する目的で、架空の内容に差し替えているということであればスルーいただければと思います。
もしそうでないとしたら、サービスアカウントキーの失効などが必要かと思いました。

**Comment by k1o0b1a9** [comment]
見ていただきありがとうございます！
少し前に勉強というか遊びついでに作ったプログラムであまりセキュリティについて意識しておりませんでした、、、

下記ファイルについてはカード番号が一部記載されており特定される可能性があるため記載内容の修正or削除します
- CSVファイル
- dotenvファイル

また、下記についてはサービスアカウントを失効させておきました
- サービスアカウントキー

確認いただきありがとうございます。
